### ISSUE TITLE
the development branch

### ISSUE THREAD

**Issue by bvogl** [EnJoIsKaTe/ProjectBA#14]
I deleted the old testBranch and created a new branch with the name development. All our new contributions to the project should be made while working in the development branch. Before we start working in our local project we should always pull the most up to date version so that no conflicts arise. When you are done working and have a state of the project that is working push to the repository. When the new feature is ready you can do a pull request. The pull to the master should only happen after someone else has reviewed the changes, at least in my opinion. What do you guys think?
So once again.

- always work and push to the development branch
- before doing anything always pull the most up to date version of the branch
- after starting a pull request wait until a code review from one of the others has happened

feel free to comment on this.

**Comment by EnJoIsKaTe** [comment]
Sounds great. I absolutely agree with you!

**Comment by bvogl** [comment]
it´s in action.
