### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by bvogl** [EnJoIsKaTe/ProjectBA#2]
We could need a Class Diagram of the existing Code and Class Structure. That would help everyone who want's to contribute to the project to get started fast. @xpanxnex would be most suitable for the task because he wrote the existing code.

**Comment by pklafs** [comment]
this is the actual class diagram of development branch
[Java Printing.pdf](https://github.com/EnJoIsKaTe/ProjectBA/files/1230309/Java.Printing.pdf)

**Comment by bvogl** [comment]
this looks great :)
